SUCCESS_EXIT_CODE = 0
UNKNOWN_ERROR_EXIT_CODE = 1
TIMEOUT_ATTEMPTS_EXIT_CODE = 2
CREDENTIALS_ERROR_EXIT_CODE = 3

LOGIN_PAGE_ID = "login-page"
UID_FIELD_ID = "txtUserId"
NEXT_BTN_ID = "btnNext"
PASSWORD_FIELD_ID = "txtLoginPassword"
CAPTCHA_FIELD_ID = "txtcaptcha"
CAPTCHA_IMAGE_ID = "imgCaptcha"
LOGIN_BTN_ID = "btnLogin"
LOGIN_ERROR_BTN_CLASS = "confirm"
LOGIN_ERROR_POPUP_CLASS = "sweet-alert"